### ISSUE TITLE
Issue with Manage Images

### ISSUE THREAD

**Issue by IMPMAC** [froala/nova-froala-field#18] opened 2019-05-06 16:26 UTC
Hi, awesome plugin.

The issue I am having is when when trying to insert an image via the browser button, I expect to see a list of images but I see an empty modal window.

Looking into the request in chromes network panel, I can see I get a 404 error when a request is made to "/nova-vendor/froala-field/image-manager?resource=articles&field=content"

<img width="981" alt="Screenshot 2019-05-06 at 17 18 46" src="https://user-images.githubusercontent.com/7000522/57239520-fe0de300-7023-11e9-8ad7-69135ddd158f.png">

**Comment by slavarazum** [comment] 2019-05-13 13:09
Did you enable attachments functionality as described in this section?
https://github.com/froala/nova-froala-field#attachments-usage

**Comment by IMPMAC** [comment] 2019-05-13 17:12
Yes I have. Including the migrations.

**Comment by slavarazum** [comment] 2019-05-14 14:43
Could you please show me your content field declaration in Nova resource?

**Comment by IMPMAC** [comment] 2019-05-14 14:44
Froala::make('Content')->withFiles('public'),

**Comment by slavarazum** [comment] 2019-05-14 15:02
Are you creating or updating resource? Maybe you routes are cached and `/nova-vendor/froala-field/image-manager` not applied. I have tried on creating and updating pages, it works fine.

**Comment by IMPMAC** [comment] 2019-05-14 15:18
My routes isn't cached. I cleared them just in case they were. 
I am Using Nova 2 and Laravel 5.8.

I know it reaches FroalaImageManagerController@index

Doing a bit of digging

The function that throws the 404 is `$request->newResource();`
Going into that the line is `abort_if(is_null($resource), 404);` that is the actual thing that throws the exception.

This is in line 51 of InteractsWithResources.php. I can see that $resource is null when I dump that variable

**Comment by slavarazum** [comment] 2019-05-15 10:52
Not file example, project example, to give me ability to reproduce the issue.

**Comment by IMPMAC** [comment] 2019-05-15 11:16
I've invited you to a github repository that you can clone and see the issue.

**Comment by slavarazum** [comment] 2019-05-17 10:18
I have found an issue. According to the latest Nova updates, logic of resource retrieve was changed, as a result it broken image-manager functionality. I will be fix it soon. Thanks for your report!

**Comment by slavarazum** [comment] 2019-05-22 17:15
Fixed in [2.2.0](https://github.com/froala/nova-froala-field/releases/tag/2.2.0)

**Closed by slavarazum** 2019-05-22 17:15 UTC

**Comment by ilikourou** [comment] 2019-07-26 11:02
Hello,

I have also problem with Image Manager functionality.
I have set up attachments and seem to be working correctly (uploading is done as expected), however when I click on the "Browse" button to bring up the image manager, the modal is empty:

![Screenshot 2019-07-26 at 13 58 13](https://user-images.githubusercontent.com/9989667/61947273-734add80-afad-11e9-854b-b7554ba23bd6.png)

On my "Network" tab in debug tools, I am getting "Status 200 OK" when hitting `image-manager?field=body`, but the response is just an empty `[]`.

Using Nova 2.0 and Laravel 5.8.27.

Thank you,
Ilias

**Comment by ilikourou** [comment] 2019-07-26 12:27
Turns out, it is the following if statement in **AttachedImagesList.php** that causes images not to appear.

```
if (! app()->runningUnitTests() and ! @getimagesize($Storage->url($file))) {
    continue;
}
```

Is there a reason this exists?

Thanks,
Ilias

**Comment by slavarazum** [comment] 2019-07-28 19:08
This condition checks whether the file is an image. So if it's not, it will not appear.
Which files not passes this check in your case?

**Comment by ilikourou** [comment] 2019-07-29 08:49
I am getting the following warning:

> "getimagesize(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution"

Note that I have not made any modifications in PHP configuration or so, it is all Laravel Homestead's default settings.

Maybe there is another way to check for the file type? 

In [PHP manual](https://www.php.net/manual/en/function.getimagesize.php) it states the following:

> Do not use getimagesize() to check that a given file is a valid image. Use a purpose-built solution such as the Fileinfo extension instead.

**Comment by slavarazum** [comment] 2019-07-29 08:59
Yes, I know about this note, but other solutions can't work with remote images, for example stored on s3 disk.

**Comment by shingsoso** [comment] 2019-08-18 04:04
> Hello,
> 
> I have also problem with Image Manager functionality.
> I have set up attachments and seem to be working correctly (uploading is done as expected), however when I click on the "Browse" button to bring up the image manager, the modal is empty:
> 
> ![Screenshot 2019-07-26 at 13 58 13](https://user-images.githubusercontent.com/9989667/61947273-734add80-afad-11e9-854b-b7554ba23bd6.png)
> 
> On my "Network" tab in debug tools, I am getting "Status 200 OK" when hitting `image-manager?field=body`, but the response is just an empty `[]`.
> 
> Using Nova 2.0 and Laravel 5.8.27.
> 
> Thank you,
> Ilias

I met the same situation , Do you guys come up any idea to solve abt that ?

**Comment by slavarazum** [comment] 2019-08-18 09:42
Try to find an issue with `getimagesize` in your PHP interpreter.

**Comment by Sinnbeck** [comment] 2019-10-25 12:35
Just an idea. Check if the driver is local and if so use path instead
```
if (config('filesystems.disks.aalund.driver') == 'local') {
        $path = $Storage->path($file);
    } else {
        $path = $Storage->url($file);
    }

    if (! app()->runningUnitTests() and ! @getimagesize($path)) {
        continue;
    }
